### ISSUE TITLE
Novakid mod break

### ISSUE THREAD

**Issue by Agent707** [IncredibleMeh/StarboundMod-RaceGameplayVariation#2]
I have feline mod and objects+ I have xbawks char creator, and the stars my Destination mod.
I got the mod to work, but when i then died and skipped the respawn sequence all the specialties of being a novakid were gone, I could heal, I didnt emitt light, i didnt test it with other races.
The mod didnt really work either witout the other mods, i just somehow made it work by putting it one by one in again.

**Comment by IncredibleMeh** [comment]
I'll look into it. 

Can you send me links to the mods you used? It'll be faster then searching for them myself and I'll be able to get right to work on checking if there are any possible compatibility issues present.

**Comment by Agent707** [comment]
btw i have windows 8.1
http://community.playstarbound.com/resources/felins.68/
http://community.playstarbound.com/resources/felins-object.1553/
http://community.playstarbound.com/resources/the-stars-my-destination-sword-and-spells.3299/  the 2.5 one
and both your mod files the modpak and the one downloadeable from github, the modpak didnt work and the time it worked only with both

**Comment by Agent707** [comment]
and 
http://community.playstarbound.com/resources/kawas-xbawks-mode-character-creator.81/

**Comment by IncredibleMeh** [comment]
Well, I found a pretty clear compatibility issues between RGV and The Stars my Destination. Both have replacements for the player_primary.lua file. The game can only choose between one file or the other, so naturally this causes problems.

Unfortunately, this is not an easily solvable issue. Both my mod and theirs so radically change things that altering the player_primary file is a necessity, so I'm very sorry to say that this issues isn't likely to have any solution soon or possibly ever.

**Comment by Agent707** [comment]
thanks could i just exchange th player_primary?
