### ISSUE TITLE
Crash when eating some food

### ISSUE THREAD

**Issue by isaac331** [IncredibleMeh/StarboundMod-RaceGameplayVariation#3]
The game instantly crashes when my human character drink coffee or eat beakseed. Tested with only this mod, no other mod, crashes. My human character once ate coffee beans, no problem. When I remove this mod and test with a new human character and spawn coffee, it was fine.

Latest stable build. I usually play in opengl 64. Win7 64 sp1.

**Comment by IncredibleMeh** [comment]
I'll be putting out a new update real soon, so I'll take a look at this and see if I can fix anything wrong.

**Comment by IncredibleMeh** [comment]
Alright, the latest update I've put out should have this issue fixed. Thanks for reporting it!
